### PR TITLE
smaller pics, price change

### PR DESCRIPTION
**Pull request by HersheysChocolateWorldLV**

### CODE REVIEW

**Comment by HersheysChocolateWorldLV** [comment]
lets gooo

**Comment by HersheysChocolateWorldLV** [comment]
now we right

**Review by typeSpindlerJ — APPROVED** [review]
lets goooo

**Review by typeSpindlerJ — COMMENTED** [review]
okay

**Comment by HersheysChocolateWorldLV** [comment]
yes

**Pull request merged**
